# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7ba6812eea242f731f1f46d4e77bc849ac454bc5b389175ebbe6adeb3a8fd8b33ff193eef8b2544a4eb21366724ae12671266f4169846afb9d23dacd9e573ce

test:
  secret_key_base: 28c8ae706763488b7ec44f447e524fc5bf957274fd82b99f1d8a9a09e57678b6d4ff05afbe9955240ea02a471d1c790e7ef2150ed935d45e6e246fc21e151d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
